import type {
  Practitioner,
  HealthEvent,
  VaccinationRecord,
  DewormingRecord,
  VitalSigns,
  Observation,
  Recommendation,
  HealthSettings,
} from "./types"

export const mockPractitioners: Practitioner[] = [
  {
    id: "pract-1",
    type: "VET",
    name: "Dr. Sophie Martin",
    phone: "+33 6 12 34 56 78",
    email: "s.martin@vetequine.fr",
    notes: "Vétérinaire équin spécialisée en médecine sportive",
  },
  {
    id: "pract-2",
    type: "FARRIER",
    name: "Jean Dupont",
    phone: "+33 6 98 76 54 32",
    email: "j.dupont@marechal.fr",
    notes: "Maréchal-ferrant, spécialiste orthopédie",
  },
  {
    id: "pract-3",
    type: "DENTIST",
    name: "Dr. Pierre Leroy",
    phone: "+33 6 45 67 89 01",
    email: "p.leroy@dentiste-equin.fr",
  },
  {
    id: "pract-4",
    type: "OSTEO",
    name: "Marie Dubois",
    phone: "+33 6 23 45 67 89",
    email: "m.dubois@osteo-cheval.fr",
    notes: "Ostéopathe équin certifiée",
  },
]

export const mockHealthEvents: HealthEvent[] = [
  {
    id: "event-1",
    horseId: "horse-1",
    category: "VACCINE",
    label: "Vaccin Grippe/Tétanos",
    plannedDate: "2025-04-15T10:00:00Z",
    status: "PLANNED",
    priority: "HIGH",
    practitionerId: "pract-1",
    cost: 85,
    currency: "EUR",
    budgetLinked: true,
    budgetOperationId: "op-health-1",
    attachments: [],
    notes: "Rappel annuel obligatoire pour les concours",
    source: "RECOMMENDER",
    recurrence: {
      type: "ANNUAL",
      interval: 1,
    },
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "event-2",
    horseId: "horse-1",
    category: "FARRIER",
    label: "Ferrure complète",
    plannedDate: "2025-02-10T14:00:00Z",
    doneDate: "2025-02-10T14:30:00Z",
    status: "DONE",
    priority: "MEDIUM",
    practitionerId: "pract-2",
    cost: 120,
    currency: "EUR",
    budgetLinked: true,
    budgetOperationId: "op-health-2",
    attachments: [],
    notes: "Fers neufs, pieds en bon état",
    source: "USER",
    recurrence: {
      type: "BIMONTHLY",
      interval: 2,
    },
    createdAt: "2025-01-20T10:00:00Z",
    updatedAt: "2025-02-10T15:00:00Z",
  },
  {
    id: "event-3",
    horseId: "horse-1",
    category: "DEWORM",
    label: "Vermifuge printemps",
    plannedDate: "2025-03-20T09:00:00Z",
    status: "PLANNED",
    priority: "HIGH",
    cost: 25,
    currency: "EUR",
    budgetLinked: true,
    attachments: [],
    notes: "Ivermectine - coproscopie préalable recommandée",
    source: "RECOMMENDER",
    recurrence: {
      type: "SEMIANNUAL",
      interval: 6,
    },
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "event-4",
    horseId: "horse-1",
    category: "DENTAL",
    label: "Contrôle dentaire annuel",
    plannedDate: "2025-05-10T11:00:00Z",
    status: "PLANNED",
    priority: "MEDIUM",
    practitionerId: "pract-3",
    cost: 95,
    currency: "EUR",
    budgetLinked: true,
    attachments: [],
    notes: "Râpe des surdents si nécessaire",
    source: "RECOMMENDER",
    recurrence: {
      type: "ANNUAL",
      interval: 1,
    },
    createdAt: "2025-01-05T10:00:00Z",
    updatedAt: "2025-01-05T10:00:00Z",
  },
  {
    id: "event-5",
    horseId: "horse-1",
    category: "VET_VISIT",
    label: "Bilan de santé semestriel",
    plannedDate: "2025-06-15T10:00:00Z",
    status: "PLANNED",
    priority: "MEDIUM",
    practitionerId: "pract-1",
    cost: 150,
    currency: "EUR",
    budgetLinked: true,
    attachments: [],
    notes: "Auscultation complète + prise de sang",
    source: "USER",
    recurrence: {
      type: "SEMIANNUAL",
      interval: 6,
    },
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2024-12-15T10:00:00Z",
  },
]

export const mockVaccinations: VaccinationRecord[] = [
  {
    id: "vacc-1",
    horseId: "horse-1",
    vaccineType: "FLU",
    date: "2024-04-15T10:00:00Z",
    lotNumber: "FLU2024-A123",
    practitionerId: "pract-1",
    nextDueDate: "2025-04-15T10:00:00Z",
    createdAt: "2024-04-15T10:30:00Z",
  },
  {
    id: "vacc-2",
    horseId: "horse-1",
    vaccineType: "TETANUS",
    date: "2024-04-15T10:00:00Z",
    lotNumber: "TET2024-B456",
    practitionerId: "pract-1",
    nextDueDate: "2025-04-15T10:00:00Z",
    createdAt: "2024-04-15T10:30:00Z",
  },
]

export const mockDewormings: DewormingRecord[] = [
  {
    id: "deworm-1",
    horseId: "horse-1",
    date: "2024-09-20T09:00:00Z",
    product: "Eqvalan",
    molecule: "Ivermectine",
    dose: "1 seringue (600kg)",
    coproBefore: {
      date: "2024-09-10T09:00:00Z",
      result: "MEDIUM",
    },
    nextDueDate: "2025-03-20T09:00:00Z",
    createdAt: "2024-09-20T09:30:00Z",
  },
]

export const mockVitalSigns: VitalSigns[] = [
  {
    id: "vital-1",
    horseId: "horse-1",
    date: "2025-02-01T08:00:00Z",
    weightKg: 520,
    bcs: 5.5,
    temperatureC: 37.8,
    heartBpm: 36,
    respBpm: 12,
    lamenessScore: 0,
    notes: "Cheval en bonne forme générale",
    createdBy: "user-1",
    createdAt: "2025-02-01T08:30:00Z",
  },
  {
    id: "vital-2",
    horseId: "horse-1",
    date: "2025-01-15T08:00:00Z",
    weightKg: 518,
    bcs: 5.5,
    temperatureC: 37.9,
    heartBpm: 38,
    respBpm: 14,
    lamenessScore: 0,
    createdBy: "user-1",
    createdAt: "2025-01-15T08:30:00Z",
  },
  {
    id: "vital-3",
    horseId: "horse-1",
    date: "2025-01-01T08:00:00Z",
    weightKg: 515,
    bcs: 5,
    temperatureC: 37.7,
    heartBpm: 36,
    respBpm: 12,
    lamenessScore: 0,
    createdBy: "user-1",
    createdAt: "2025-01-01T08:30:00Z",
  },
]

export const mockObservations: Observation[] = [
  {
    id: "obs-1",
    horseId: "horse-1",
    date: "2025-02-15T08:00:00Z",
    type: "NOTE",
    text: "Cheval en pleine forme, très dynamique au paddock",
    attachments: [],
    createdBy: "user-1",
    createdAt: "2025-02-15T08:30:00Z",
    priority: "LOW",
  },
  {
    id: "obs-2",
    horseId: "horse-1",
    date: "2025-02-10T18:00:00Z",
    type: "SYMPTOM",
    text: "Légère toux après le travail, à surveiller",
    attachments: [],
    createdBy: "user-1",
    createdAt: "2025-02-10T18:30:00Z",
    priority: "MEDIUM",
  },
]

export const mockRecommendations: Recommendation[] = [
  {
    id: "reco-1",
    horseId: "horse-1",
    title: "Vermifuge de printemps",
    detail:
      "Le printemps approche, il est temps de planifier le vermifuge saisonnier. Une coproscopie préalable est recommandée pour adapter le traitement.",
    category: "SEASONAL",
    priority: "HIGH",
    suggestedDate: "2025-03-20T09:00:00Z",
    action: "PLAN_EVENT",
    basedOn: ["SEASON", "HISTORY"],
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "reco-2",
    horseId: "horse-1",
    title: "Contrôle du poids",
    detail:
      "Le poids de votre cheval a augmenté de 5kg ce mois-ci. Continuez à surveiller pour maintenir une condition corporelle optimale.",
    category: "PERIODIC",
    priority: "MEDIUM",
    action: "MARK_DONE",
    basedOn: ["VITALS"],
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "reco-3",
    horseId: "horse-1",
    title: "Hydratation en hiver",
    detail:
      "Températures froides : vérifiez que l'eau n'est pas gelée et que votre cheval boit suffisamment (20-50L/jour). Vous pouvez tiédir légèrement l'eau pour l'encourager.",
    category: "SEASONAL",
    priority: "MEDIUM",
    action: "READ_MORE",
    basedOn: ["SEASON", "WEATHER"],
    createdAt: "2025-01-15T10:00:00Z",
  },
]

export const mockHealthSettings: HealthSettings = {
  horseId: "horse-1",
  notifications: {
    reminders: true,
    tips: true,
    weeklyReport: true,
    monthlyReport: true,
    quietHours: {
      from: "22:00",
      to: "07:00",
    },
  },
  calendarSync: {
    google: false,
    ical: false,
  },
  sensitivity: {
    tempHigh: 38.5,
    weightLossPct: 5,
  },
  share: [],
  createdAt: "2024-01-01T00:00:00Z",
  updatedAt: "2025-01-01T00:00:00Z",
}
