import type { TrainingSession, TrainingSettings, TrainingRecommendation } from "./types"

export const mockSessions: TrainingSession[] = [
  {
    id: "sess-1",
    horseId: "horse-1",
    title: "Trotting forêt",
    type: "EXTERIOR",
    mode: "MOUNTED",
    status: "DONE",
    plannedStart: null,
    plannedEnd: null,
    start: "2025-01-18T07:10:00Z",
    end: "2025-01-18T08:22:00Z",
    durationSec: 4320, // 1h12
    distanceM: 11800,
    elevationPosM: 160,
    avgSpeedKmh: 9.8,
    maxSpeedKmh: 36.5,
    gpsTrackId: "track-1",
    hrAvgBpm: 122,
    hrMaxBpm: 168,
    hrZones: [
      { z: "Z1", sec: 600 },
      { z: "Z2", sec: 2460 },
      { z: "Z3", sec: 1200 },
      { z: "Z4", sec: 60 },
      { z: "Z5", sec: 0 },
    ],
    gaits: {
      walkSec: 900,
      trotSec: 2460,
      canterSec: 540,
      haltSec: 420,
    },
    intervals: [],
    calories: {
      horseKcal: 3200,
      riderKcal: 450,
    },
    intensity: "MODERATE",
    trainingLoad: 245,
    rpe: 6,
    surface: "TRAIL",
    weather: {
      tempC: 8,
      humidity: 75,
      windKph: 12,
      conditions: "Nuageux",
    },
    notes: "Bon rythme, récupération rapide",
    attachments: [],
    cost: 0,
    currency: "EUR",
    budgetLinked: false,
    budgetOperationId: null,
    shareableImageId: null,
    source: "PHONE_GPS",
    externalRef: null,
    clubId: null,
    createdBy: "user-1",
    createdAt: "2025-01-18T08:22:00Z",
    updatedAt: "2025-01-18T08:22:00Z",
  },
  {
    id: "sess-2",
    horseId: "horse-1",
    title: "Cours CSO",
    type: "CSO",
    mode: "MOUNTED",
    status: "DONE",
    plannedStart: "2025-01-16T18:00:00Z",
    plannedEnd: "2025-01-16T19:00:00Z",
    start: "2025-01-16T18:05:00Z",
    end: "2025-01-16T18:50:00Z",
    durationSec: 2700, // 45 min
    distanceM: 2400,
    elevationPosM: 0,
    avgSpeedKmh: 5.3,
    maxSpeedKmh: 18.2,
    gpsTrackId: null,
    hrAvgBpm: 135,
    hrMaxBpm: 182,
    hrZones: [
      { z: "Z1", sec: 300 },
      { z: "Z2", sec: 900 },
      { z: "Z3", sec: 1200 },
      { z: "Z4", sec: 300 },
      { z: "Z5", sec: 0 },
    ],
    gaits: {
      walkSec: 900,
      trotSec: 1200,
      canterSec: 600,
      haltSec: 0,
    },
    intervals: [],
    calories: {
      horseKcal: 2100,
      riderKcal: 320,
    },
    intensity: "HARD",
    trainingLoad: 310,
    rpe: 8,
    surface: "ARENA_SAND",
    weather: null,
    notes: "Parcours 1m10, très bien passé",
    attachments: [],
    cost: 90,
    currency: "EUR",
    budgetLinked: true,
    budgetOperationId: "op-training-1",
    shareableImageId: null,
    source: "MANUAL",
    externalRef: null,
    clubId: null,
    createdBy: "user-1",
    createdAt: "2025-01-16T18:50:00Z",
    updatedAt: "2025-01-16T18:50:00Z",
  },
  {
    id: "sess-3",
    horseId: "horse-1",
    title: "Dressage",
    type: "DRESSAGE",
    mode: "MOUNTED",
    status: "PLANNED",
    plannedStart: "2025-01-20T14:00:00Z",
    plannedEnd: "2025-01-20T15:00:00Z",
    start: null,
    end: null,
    durationSec: 0,
    distanceM: 0,
    elevationPosM: 0,
    avgSpeedKmh: 0,
    maxSpeedKmh: 0,
    gpsTrackId: null,
    hrAvgBpm: 0,
    hrMaxBpm: 0,
    hrZones: [],
    gaits: {
      walkSec: 0,
      trotSec: 0,
      canterSec: 0,
      haltSec: 0,
    },
    intervals: [],
    calories: {
      horseKcal: 0,
      riderKcal: 0,
    },
    intensity: "MODERATE",
    trainingLoad: 0,
    rpe: 0,
    surface: "ARENA_SAND",
    weather: null,
    notes: null,
    attachments: [],
    cost: 0,
    currency: "EUR",
    budgetLinked: false,
    budgetOperationId: null,
    shareableImageId: null,
    source: "MANUAL",
    externalRef: null,
    clubId: null,
    createdBy: "user-1",
    createdAt: "2025-01-19T10:00:00Z",
    updatedAt: "2025-01-19T10:00:00Z",
  },
]

export const mockSettings: TrainingSettings = {
  horseId: "horse-1",
  watchIntegration: {
    appleHealth: false,
    allowBackground: true,
  },
  notifications: {
    reminders: true,
    tips: true,
    weeklyReport: true,
    monthlyReport: true,
    quietHours: {
      from: "22:00",
      to: "07:00",
    },
  },
  gaitThresholds: {
    walkMaxKmh: 7,
    trotMaxKmh: 17,
    canterMinKmh: 17,
  },
  hrZones: [
    { z: "Z1", min: 40, max: 80 },
    { z: "Z2", min: 81, max: 110 },
    { z: "Z3", min: 111, max: 140 },
    { z: "Z4", min: 141, max: 170 },
    { z: "Z5", min: 171, max: 240 },
  ],
  loadModel: {
    method: "CAVALY",
    alpha: 0.9,
  },
  calendarSync: {
    google: false,
    ical: false,
  },
  shareDefaultHashtags: ["#HorseRiding", "#Cavaly"],
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-01-19T00:00:00Z",
}

export const mockRecommendations: TrainingRecommendation[] = [
  {
    id: "rec-1",
    horseId: "horse-1",
    title: "Attention à la surcharge",
    detail:
      "Votre charge d'entraînement a augmenté de 12% cette semaine. Pour prévenir les blessures, il est recommandé de ne pas dépasser +10% par semaine. Prévoyez une séance de récupération active demain.",
    category: "PREVENTION",
    priority: "HIGH",
    suggestedDate: "2025-01-20T00:00:00Z",
    action: "ADJUST_INTENSITY",
    basedOn: ["HISTORY", "SCIENCE_RULES"],
    feedback: null,
    createdAt: "2025-01-19T08:00:00Z",
  },
  {
    id: "rec-2",
    horseId: "horse-1",
    title: "Échauffement prolongé recommandé",
    detail:
      "Avec les températures actuelles (5°C), il est conseillé d'allonger l'échauffement de 5-10 minutes. Commencez par 20 minutes de pas et trot avant tout effort intense.",
    category: "DAILY",
    priority: "MEDIUM",
    suggestedDate: null,
    action: "READ_MORE",
    basedOn: ["WEATHER", "SCIENCE_RULES"],
    feedback: null,
    createdAt: "2025-01-19T07:00:00Z",
  },
  {
    id: "rec-3",
    horseId: "horse-1",
    title: "Planifier une séance d'endurance",
    detail:
      "Vous n'avez pas fait de sortie longue (>1h30) depuis 2 semaines. Pour maintenir le cardio, planifiez une séance de trotting en extérieur cette semaine.",
    category: "WEEKLY",
    priority: "MEDIUM",
    suggestedDate: "2025-01-21T00:00:00Z",
    action: "PLAN_SESSION",
    basedOn: ["HISTORY", "DISCIPLINE"],
    feedback: null,
    createdAt: "2025-01-19T08:00:00Z",
  },
]
